cfg/auth.py, transfer_results_module/transfer_results.py, utils/error_handling.py
This fixes an issue that occured during the last days.
Our old transfer results script was not able to import the results to mysql as quick as new data came into firebase. This was really critical and our server was using 100% all the time.
In the old script each result was transfered to mysql individually and afterwards deleted in firebase. This was not scalable.
In the new script the results from firebase are saved into a textfile. This textfile is first uploaded to an empty table in mysql ('raw_results'), afterwards we insert the items from the raw results table to the results table and check for duplicates.
Finally all entries are deleted in firebase using the "update" function. Removing items individually was not fast enough.
=> Fix transfer results scalability (fixes #15)

mapswipe_workers/.pre-commit-config.yaml, mapswipe_workers/setup.cfg
Add setup.cfg to configure python plugins and utils like flake8.
Removed arguments from pre-commit-hook commands because of setup.cfg.
=> Code style

mapswipe_workers/mapswipe_workers/definitions.py, mapswipe_workers/mapswipe_workers/mapswipe_workers.py, mapswipe_workers/mapswipe_workers/project_types/build_area/build_area_project.py, mapswipe_workers/mapswipe_workers/project_types/change_detection/change_detection_project.py, mapswipe_workers/mapswipe_workers/project_types/footprint/footprint_project.py
- Add project types as global var to definitions.
- Run Black.
- Make use of PROJECT_TYPES in mapswipe_workers.py
- Remove not needed imports in definitions.py and mapswipe_workers.py
=> Add project types as global var to definitions.

mapswipe_workers/Dockerfile, mapswipe_workers/mapswipe_workers/definitions.py, mapswipe_workers/mapswipe_workers/firebase_to_postgres/transfer_results.py, mapswipe_workers/mapswipe_workers/mapswipe_workers.py, mapswipe_workers/mapswipe_workers/utils/user_management.py
In this pull request a couple of issues, which arose due to many changes in the code during the last pull requests starting with "Archive feature", are adressed.
- Use official gdal docker image from osgeo.
- Set C.UTF-8 locale as default needed by the Click library.
- Avoid circular imports arising during import of project_types in definitions.py and import of definitions.py in project_types.
- Correct wrong import location.
- Change arguement type from click.Path to string due to unresolved error.
- add archive and run commands to cli group of commands.
=> Circular imports

mapswipe_workers/mapswipe_workers/firebase_to_postgres/transfer_results.py, mapswipe_workers/scripts/archive_old_projects.py
* Run a script to move the old projects (created before we switched to v2) to the new Firebase projects path.
* Delete the old groups
* Delete old results, imports, announcements
* Don't touch old user data
This workflow would be run once for the production environment. I'm not sure where is the best place to put it. I put it to a new directory `scripts` for now.
=> add script to archive old firebase projects

mapswipe_workers/mapswipe_workers/base/base_project.py, mapswipe_workers/mapswipe_workers/definitions.py, mapswipe_workers/mapswipe_workers/mapswipe_workers.py, mapswipe_workers/mapswipe_workers/utils/geojson_functions.py, mapswipe_workers/scripts/add_project_geometries_to_api.py, mapswipe_workers/scripts/mapswipe_to_hot_tm_project.py
This implements #333
* tasking manager geometries are simpler (bounding box instead of convex hull)
* use a coordinate precision of 7 digits
* we additionally export the project extent as geojson file during project creation
Further it fixes a small bug in setting up the logger.
@Matthias-Schaub could you review this in the coming days?
=> Tasking manager geometries

firebase/database.rules.json, manager_dashboard/manager_dashboard/create.html, manager_dashboard/manager_dashboard/index.html, manager_dashboard/manager_dashboard/js/forms.js, manager_dashboard/manager_dashboard/js/project-management.js, manager_dashboard/manager_dashboard/js/team-management.js, manager_dashboard/manager_dashboard/js/uploadProjects.js, manager_dashboard/manager_dashboard/manage.html, manager_dashboard/manager_dashboard/teams.html, mapswipe_workers/mapswipe_workers/mapswipe_workers.py, mapswipe_workers/mapswipe_workers/project_types/base/project.py, mapswipe_workers/mapswipe_workers/utils/team_management.py, mapswipe_workers/mapswipe_workers/utils/user_management.py, mapswipe_workers/tests/integration/test_firebase_db_rules.py, mapswipe_workers/tests/integration/test_team_management.py
This sets the basic structure needed from MapSwipe back end side to allow for private projects. This refers to #392 
* adds functions to mapswipe_workers cli to set up new teams and manage which users are members
* extends manager dashboard to create and display private projects and to display teams including their members
* adjusts firebase database rules to account for new endpoint at `v2/teams`
* adjusts project creation workflow to set status of private projects to `private_inactive` once created
Team set up is currently handled only by mapswipe_workers cli. There you can also renew the `teamToken` attribute if needed.
=> Feature private projects

mapswipe_workers/mapswipe_workers/generate_stats/project_stats.py, mapswipe_workers/mapswipe_workers/generate_stats/tasking_manager_geometries.py, mapswipe_workers/mapswipe_workers/utils/geojson_functions.py
This PR uses compression for the files that are exported.
Not all files are compressed, but only these that are relatively big and not used much. In particular we do not compress the tasking manager geometries files that are used by project manager most frequently.
However, the biggest files are `results`, `tasks` and `agg_results` and these (and `groups` and `users`) will be compressed from now on.
Once this PR is merged we need to run the `generate-stats` command for all projects. Then we should remove all "old" files that didn't use compression.
```
docker-compose run -d mapswipe_workers mapswipe_workers --verbose generate-stats-all-projects
```
```
rm -rf mapswipe-data/api/agg_results/*.csv
rm -rf mapswipe-data/api/agg_results/*.geojson
rm -rf mapswipe-data/api/tasks/*.csv
rm -rf …
```
=> compress files for export with gzip #451

mapswipe_workers/mapswipe_workers/project_types/base/project.py, mapswipe_workers/tests/integration/fixtures/footprint/projectDrafts/footprint.json, mapswipe_workers/tests/integration/test_create_build_area_project.py, mapswipe_workers/tests/integration/test_create_footprint_project.py
this refers to #344 
Basically, we do not need to upload tasks to Firebase for build area projects, since this is not used by the current version of the app anymore.
=> do not upload tasks for projects of type build_area

firebase/database.rules.json, mapswipe_workers/locust_files/load_testing.py, mapswipe_workers/mapswipe_workers/firebase_to_postgres/transfer_results.py
this refers to #482 
[Locust](https://locust.io/) is used to test how many results the `transfer_results` function can handle.
For testing we set up new users in Firebase, that do some mapping in a real project. I tested the "old" version of the transfer results function which used a transaction function and the new version, where we just delete the transfered groups within an update function.
Note: Firebase DB rules needed to be changed to account for an missing index on the `requiredCount` of a group. It's a bit weird, why this has worked before. Is the app not using the requiredCount?
* 25 users, spawn rate: 1user/sec
* each user's wait time between 30 sec and 120 sec
* ~0.3 requests (groups results uploaded) per second
* backend needs 3 attempts to transfer results within one …
=> WIP: Load testing with locust

mapswipe_workers/mapswipe_workers/utils/api_calls.py
=> Changed comment to hashtags and moved to right section

mapswipe_workers/mapswipe_workers/firebase_to_postgres/transfer_results.py
the previous solution didn't remove all invalid tasks. There could have been a situation where the task_id was twice listed in the results. E.g. one time for a valid result and another time for an invalid result. In such a situation the invalid result would not have been removed. 
This triggered many error messages in Sentry because the transfer of results from firebase to postgres is performed every 2 minutes (and failed every two minutes for the project)
=> adjust sql query to make sure to select all invalid results to delete

Makefile
This PR is to track the creation of a `Makefile` which will contain important commands that we use regularly to manage mapswipe backend servers.
The goal is not to be exhaustive, merely to provide a simple list of daily actions that could be managed by more than 1-2 people, and therefore reduce bottlenecks.
Feel free to suggest additions in the PR, even if you don't know how to implement.
=> Add skeleton Makefile for common commands

django/apps/aggregated/management/commands/update_aggregated_data.py, mapswipe_workers/mapswipe_workers/firebase_to_postgres/transfer_results.py, nginx/nginx.conf.template
- https://github.com/mapswipe/mapswipe-meta/issues/93
> confirm that "Total area swiped" does not include stats from the footprint validation type missions. that is, it should only be 'build area missions sq km' + 'change detection missions sq km' + 'completeness missions sq km'.
- Nginx skip caching 502 and 503.
NOTE:
To clear out pre-calculate aggregated data.
- Users Stats
```sql
UPDATE
aggregated_aggregateduserstatdata
SET area_swiped = 0
WHERE project_id in (
SELECT project_id FROM projects where project_type = 2
)
```
- UserGroups Stats
```sql
UPDATE
aggregated_aggregatedusergroupstatdata
SET area_swiped = 0
WHERE project_id in (
SELECT project_id FROM projects where project_type = 2
)
```
=> Skip footprint mission area swiped.

django/apps/aggregated/management/commands/update_aggregated_data.py
For defining the threshold for outliers using `95_percent`
Used by TASK_GROUP_METADATA_QUERY
|project_type|median|95_percent|avg|
|------------|------|----------|---|
|1|00:00:00.208768|00:00:01.398161|00:00:28.951521|
|2|00:00:01.330297|00:00:06.076814|00:00:03.481192|
|3|00:00:02.092967|00:00:11.271081|00:00:06.045881|
It took around 14 Hours to re-calculate all the stats using a single SQL query.
It might take more by Django as we are calculating in batch.
Steps are as:
```sql
DELETE FROM aggregated_aggregatedtracking;
DELETE FROM aggregated_aggregatedusergroupstatdata;
DELETE FROM aggregated_aggregateduserstatdata;
```
```bash
tmux  # It can take some time, so tmux/screen is useful here
docker-compose exec django ./manage.py update_aggregated_data
```
=> Add threshold for time-spent calculation

manager-dashboard/app/Base/configs/projectTypes.ts, manager-dashboard/app/views/NewProject/index.tsx, manager-dashboard/app/views/NewProject/utils.ts, manager-dashboard/app/views/NewTutorial/index.tsx, manager-dashboard/app/views/NewTutorial/utils.ts
With these changes you can specifiy which projects types are supported in the manager dashboard. There is the `default` mapswipe configuration which supports the know 4 project types (build_area, footprint, change_detection, completeness).
This change will allow us to add more project types in the future step by step, but gives the option to not directly deploy them to the manager dashboard or make them publicly available.
=> Configure project types available in manager dashboard

manager-dashboard/app/views/NewProject/BasicProjectInfoForm/index.tsx, manager-dashboard/app/views/NewProject/index.tsx
This is part of a WIP to refactor each project type into a separate 'New Project' subform.
This creates a reusable BasicProjectInformationForm sub-component of the 'New Project' view that collects contains all inputs that are shared among projects of all types.
Refers to #665
=> refactor(manager-dashboard): create reusable BasicProjectInformationForm component

manager-dashboard/app/components/GeoJsonFileInput/index.tsx, manager-dashboard/package.json, manager-dashboard/yarn.lock
We are currently using `@turf/boolean-valid` for validation of geojson.
We have a false negative for a geojson. (For more information https://mapswipe.slack.com/archives/C0HCW2CJJ/p1677586146742749?thread_ts=1677518532.043429&cid=C0HCW2CJJ)
The library does not specify what is wrong with the geojson which is not very useful.
Changing the geojson validation library from `@turf/boolean-valid` to `@placemarkio/check-geojson` so that we get better errors and avoid issue with the false negative.
=> Use a different geojson validator

postgres/scripts/backtrack_user_group_mapping_sessions.sql
Issue:
- https://github.com/mapswipe/mapswipe-meta/issues/13
Before running the SQL script, generate a user-group mapping session table CSV dump (If we need to revert back changes)
```bash
docker-compose exec postgres psql -U mapswipe_workers mapswipe -c '\copy (SELECT * FROM mapping_sessions_user_groups) to STDOUT CSV HEADER;' > /tmp/user-group-session-data-`date +%Y-%m-%d.%H:%M:%S`.csv
```
Running the SQL Script and aggregated data calculation
```bash
docker-compose exec -T postgres bash -c 'psql -U $POSTGRES_USER $POSTGRES_DB' < postgres/scripts/backtrack_user_group_mapping_sessions.sql
docker-compose exec django ./manage.py update_aggregated_data
```
=> Add script for backtrack calculation

django/apps/aggregated/management/commands/update_aggregated_data.py, django/apps/aggregated/management/commands/update_project_groups_data.py, docker-compose.yaml
- Address https://mapswipe.slack.com/archives/C03GP23EJPP/p1687289297561789
> [This user](https://community.mapswipe.org/user/GkT5pS3Z8Yfm7M6JEPgSH1r7WX03/?from=2023-06-13&to=2023-06-20) shared that they "left MapSwipe open" on Sunday and now his stats are showing 22 hours.
- Run project groups data calculation (Runtime: 5-6 hours for Database with 8CPU 16GB VM)
```bash
time docker-compose run --rm django ./manage.py update_project_groups_data
```
- Reset aggregated tracking point
```SQL
TRUNCATE TABLE aggregated_aggregatedtracking;
``` 
- Run aggregated data calculation (Runtime: 13-15 min for Database with 8CPU 16GB VM)
```bash
time docker-compose run --rm django ./manage.py update_aggregated_data
```
=> Fix footprint time threshold calculation logic

mapswipe_workers/python_scripts/add_missing_usernames_in_firebase.py, mapswipe_workers/python_scripts/update_task_contribution_count_in_firebase.py
This fixes #687 
check how many users are affected:
```
select 
count(*)
from users u 
where 1=1
and username = ''
and user_id not LIKE 'osm:%'
and created >= '2024-01-01'
;
```
--> 403 users
Post-merge steps:
```
docker compose run -d mapswipe_workers_creation python python_scripts/update_task_contribution_count_in_firebase.py.
```
```
docker compose run -d mapswipe_workers_creation python python_scripts/add_missing_usernames_in_firebase.py
```
=> fix missing usernames v2

mapswipe_workers/mapswipe_workers/utils/process_mapillary.py, mapswipe_workers/tests/unittests/test_process_mapillary.py
Currently, all Mapillary sequences that intersect with the AoI are used in the project. With this PR the retireved data locations are clipped to the AoI.
=> feat: clip image locations to aoi

mapswipe_workers/mapswipe_workers/project_types/street/project.py, mapswipe_workers/mapswipe_workers/utils/process_mapillary.py, mapswipe_workers/tests/unittests/test_process_mapillary.py
Add the possibility to filter by creatorId
=> feat: add filter by creator_id

manager-dashboard/app/Base/configs/projectTypes.ts, manager-dashboard/app/Base/styles.css, manager-dashboard/app/components/Calendar/CalendarDate/index.tsx, manager-dashboard/app/components/Calendar/CalendarDate/styles.css, manager-dashboard/app/components/Calendar/index.tsx, manager-dashboard/app/components/Calendar/styles.css, manager-dashboard/app/components/DateRangeInput/index.tsx, manager-dashboard/app/components/DateRangeInput/predefinedDateRange.ts, manager-dashboard/app/components/DateRangeInput/styles.css, manager-dashboard/app/utils/common.tsx, manager-dashboard/app/views/NewProject/index.tsx, manager-dashboard/app/views/NewProject/styles.css, manager-dashboard/app/views/NewProject/utils.ts
Adds the functionality to create new projects drafts of type "Street" with the manager dashboard.
In particular, this adds an input section for Mapillary image filter parameters to the project creation form that allows setting filters on data range, Mapillary image creator id and Mapillary organisation id, (panorama) format of the images, and a sampling threshold.
A new date range input component has been adapted from [toggle-ui](https://github.com/toggle-corp/toggle-ui/tree/develop/src/components/DateRangeInput).
This PR does not yet include new tutorial drafts for Street projects. There is a dummy street project tutorial on the MapSwipe dev instance that allows testing project draft creation.
=> Create Street project drafts with the Manager Dashboard

manager-dashboard/app/views/NewProject/index.tsx, manager-dashboard/app/views/NewProject/utils.ts
The Mapillary image filter section on the new project form for projects of type Street has a checkbox input to determine whether Mapillary imagery should be filtered for 360° panoramic images or not.
Before this fix, leaving the box unchecked would result in adding a `isPano` field with the value `false`  to the project draft, which in return would mean that the python creation worker would filter available imagery for non-panoramic images.
With this fix, `isPano` is **not** added to the project draft if the checkbox is left unmarked, meaning that both panoramic and non-panoramic images are used, as was originally intended.
=> fix(manager-dashboard): correctly set isPano for street projects

manager-dashboard/app/views/NewProject/index.tsx, manager-dashboard/app/views/NewProject/utils.ts
This adds an input for `randomizeOrder` to the New Project form for projects of type Street in the Manager Dashboard.
Depends on #989
=> Add randomizeOrder input for new Street projects

mapswipe_workers/mapswipe_workers/utils/process_mapillary.py, mapswipe_workers/tests/unittests/test_process_mapillary.py
get_image_metadata() raises CustomError instead of ValueError, so that errors are correctly caught in run_create_projects()
=> Fix Mapillary image metadata error handling

manager-dashboard/app/views/NewProject/utils.ts, manager-dashboard/app/views/NewTutorial/ScenarioPageInput/index.tsx, manager-dashboard/app/views/NewTutorial/index.tsx, manager-dashboard/app/views/NewTutorial/utils.ts, mapswipe_workers/sample_data/street/README.md, mapswipe_workers/sample_data/street/street_tutorial_sample_scenario.geojson
Enables creation of tutorial drafts for projects of type Street from the Manager Dashboard.
The PR includes a sample Street tutorial screens/scenario GeoJSON, as well as a README with instructions on how such scenario files can be created.
The Scenario Pages section of the New Tutorial view does not include scenario page preview for Street project screens, as the project type is currently web only. Previews for scenario screens of other project types are based on the design of the tutorial in the mobile app version.
=> Feature/manager dashboard/street tutorial

mapswipe_workers/python_scripts/extract_project_population_stats.py
This adds a script to extract the estimated population living within the boundaries of a MapSwipe project from WorldPop data. This may be helpful as one indication of MapSwipe project impact.
WorldPop 1km data is downloaded locally if not yet existent. Compared to the WorldPop 100m country-level data sets, the 1 km data set is rather coarse, but much easier to handle. In some cases (e.g. a MapSwipe project in a more sparsely populated area that directly borders a densely populated city), this may lead to inaccurate values, but in most cases the approximation should be good enough.
MapSwipe Project IDs are provided via the -t flag in a text file containing IDs in this manner: 
`-O8kulfxD4zRYQ2T1aXf, -O8kyOCreRGklW15n8RU, -O8kzSy9105axIPOAJjO, -OAwWv9rnJqPXTpWxO8-`
=> feat: add script to extract population stats for projects

firebase/functions/src/index.ts
The logger should log errors in the following format:
```bash
message[Discarding result because of suspicious speed.] mappingSpeed[0.01] project[-OK2zqCievx0TUrnF61i] user[-evUrnF6OK2zTi1iqx0] group[-1iqx0evUrnF6OK2zTi] version[v2.0.0-beta]
```
=> Create logger function to include more information

django/apps/aggregated/management/commands/update_aggregated_data.py
This sets a value of maximum 65 seconds per task to be counted into user mapping time stats for each completed task group in Street projects. The value is derived from the 95th percentile of mapping time per task in existing Street project contributions. That value is expected to decrease as soon as more contributions to Street projects are received.
Closes #1017
=> fix: set factor for time_spent_max_allowed in street projects
