mapswipe/python-mapswipe-workers

- readme.md
- utils/send_slack_message.py
added a username to the slack bot
> Slack client setting

- import_module/create_groups.py
I looked at the groups creation and added few lines to avoid zero division errors.
> fix zero division error, add check and also fix multipolygon issue #11

- LICENSE
This changes the license of the Python workers from GNU v2 to Apache v2.
> Update LICENSE to Apache

- readme.md
I add the project to waffle.io. It is an extended ticket board working on top of GitHub issues and free for open source projects.
Let me know what you think!
> Add waffle.io board

- import_module/create_groups.py
- import_module/run_import.py
There are some changes that have not been commited to the master related to the KML import issue Gabor had recently.
@ericboucher it seems that you changed something directly on the server. Is this correct?
And do we need all those print statements?
> changes from master

- manager_dashboard/manager_dashboard/create.html
- manager_dashboard/manager_dashboard/js/forms.js
this is a simple fix to check if files are too large when creating a new project.
I set the limit to 2.5 MB.
> Fix file too large

- manager_dashboard/manager_dashboard/create.html
- manager_dashboard/manager_dashboard/js/forms.js
- mapswipe_workers/mapswipe_workers/project_types/build_area/build_area_project.py
- mapswipe_workers/mapswipe_workers/project_types/change_detection/change_detection_project.py
maximum zoom level is set to 22 now.
> Fix max zoomlevel

- docker-compose.yaml
- mapswipe_workers/mapswipe_workers/base/base_project.py
- mapswipe_workers/mapswipe_workers/mapswipe_workers.py
- mapswipe_workers/setup.py
- Scheduling is now only used for run() (create projects, transfer results and generate stats).
- Code has been simplefied.
- Black and flake8 compatible.
> Rewrite of the cli mapswipe_workers.py.

- firebase/database.rules.json
> Update database rules for the leaderboard v2

- mapswipe_workers/mapswipe_workers/mapswipe_workers.py
> send success message from within try block #289

- mapswipe_workers/mapswipe_workers/firebase_to_postgres/archive_project.py
> Fix archive projects

- mapswipe_workers/mapswipe_workers/utils/tile_functions.py
> Google format custom tile servers

- mapswipe_workers/mapswipe_workers/definitions.py
- mapswipe_workers/mapswipe_workers/mapswipe_workers.py
- mapswipe_workers/mapswipe_workers/utils/slack_helper.py
- mapswipe_workers/tests/test_progress_notification.py
Hey @laurentS,
this one is for you. Will probably save you a lot of time in the future. :) You want to take a quick look?
> send project progress notifications #330

- .gitignore
- manager_dashboard/manager_dashboard/create.html
- manager_dashboard/manager_dashboard/css/mapswipe.css
- manager_dashboard/manager_dashboard/js/forms.js
- manager_dashboard/manager_dashboard/js/uploadProjects.js
- mapswipe_workers/.pre-commit-config.yaml
> Project creation form

- mapswipe_workers/mapswipe_workers/generate_stats/project_stats.py
> add quadkey to aggregated results

- firebase/functions/index.js
- mapswipe_workers/mapswipe_workers/firebase_to_postgres/transfer_results.py
Adjust back end to account for slight changes in app. #382 
https://github.com/mapswipe/mapswipe/pull/237
> Timestamp attribute

- mapswipe_workers/mapswipe_workers/firebase_to_postgres/transfer_results.py
this is a work around for #387
> use correct function in sentry to capture exception

- mapswipe_workers/mapswipe_workers/firebase_to_postgres/transfer_results.py
- mapswipe_workers/mapswipe_workers/firebase_to_postgres/update_data.py
- mapswipe_workers/mapswipe_workers/generate_stats/generate_stats.py
- mapswipe_workers/mapswipe_workers/generate_stats/overall_stats.py
- mapswipe_workers/mapswipe_workers/generate_stats/project_stats.py
- mapswipe_workers/mapswipe_workers/generate_stats/project_stats_by_date.py
- mapswipe_workers/mapswipe_workers/generate_stats/tasking_manager_geometries.py
- mapswipe_workers/mapswipe_workers/generate_stats/user_stats.py
- mapswipe_workers/mapswipe_workers/mapswipe_workers.py
- mapswipe_workers/mapswipe_workers/project_types/arbitrary_geometry/grouping_functions.py
- mapswipe_workers/mapswipe_workers/project_types/base/group.py
- mapswipe_workers/mapswipe_workers/project_types/base/project.py
- mapswipe_workers/mapswipe_workers/project_types/base/task.py
- mapswipe_workers/mapswipe_workers/project_types/base/tile_server.py
- mapswipe_workers/mapswipe_workers/project_types/tile_map_service_grid/group.py
- mapswipe_workers/mapswipe_workers/project_types/tile_map_service_grid/project.py
- mapswipe_workers/mapswipe_workers/project_types/tile_map_service_grid/tutorial.py
- mapswipe_workers/mapswipe_workers/utils/geojson_functions.py
- mapswipe_workers/mapswipe_workers/utils/team_management.py
- mapswipe_workers/mapswipe_workers/utils/tile_functions.py
- mapswipe_workers/mapswipe_workers/utils/user_management.py
- mapswipe_workers/python_scripts/add_usernames_in_firebase.py
- mapswipe_workers/python_scripts/archive_old_projects.py
- mapswipe_workers/python_scripts/tasks_to_geojson.py
- mapswipe_workers/tests/integration/tear_down.py
- mapswipe_workers/tests/integration/test_firebase_db_rules.py
- mapswipe_workers/tests/integration/test_team_management.py
- mapswipe_workers/tests/integration/test_transfer_results.py
Code is left with only
```
./mapswipe_workers/project_types/arbitrary_geometry/grouping_functions.py:64:9: E722 do not use bare 'except'
./mapswipe_workers/project_types/arbitrary_geometry/grouping_functions.py:80:5: E722 do not use bare 'except'
```
since these are probably fixes a more expert person than me should make.
> Make code compatible with black and flake8. Fixes #327

- mapswipe_workers/.pre-commit-config.yaml
- mapswipe_workers/mapswipe_workers/mapswipe_workers.py
- mapswipe_workers/mapswipe_workers/project_types/base/project.py
- mapswipe_workers/mapswipe_workers/utils/geojson_functions.py
- mapswipe_workers/mapswipe_workers/utils/tile_functions.py
- mapswipe_workers/tests/integration/run_tests.sh
- mapswipe_workers/tests/integration/set_up.py
- mapswipe_workers/tests/integration/test_archive_project.py
- mapswipe_workers/tests/integration/test_delete_project.py
- mapswipe_workers/tests/integration/test_transfer_results.py
- mapswipe_workers/tests/integration/test_update_user_data.py
- mapswipe_workers/tests/unittests/test_firebase_connection.py
- mapswipe_workers/tests/unittests/test_user_stats.py
Wait for Firebase Functions to complete during test setup.
Fix for #416.
> Adresses test fail due to late Firebase Function completion.

- mapswipe_workers/sample_data/build_area/default_build_area_tutorial_screens.json
Tracked-on: https://github.com/mapswipe/mapswipe/issues/418
> Updated tutorial text

- firebase/functions/index.js
- mapswipe_workers/mapswipe_workers/project_types/base/project.py
Firebase Functions
Refactor counter for first time user contribution to a project into seperate database trigger function.
Mapswipe Workers  Base Class:
Init contributorCount with 0.
> Fix for "Project Contributor Count is broken" #420

- firebase/functions/index.js
Improve readability of the code.
> Make Firebase Function code more readable

- mapswipe_workers/mapswipe_workers/firebase_to_postgres/transfer_results.py
- mapswipe_workers/mapswipe_workers/mapswipe_workers.py
- mapswipe_workers/mapswipe_workers/project_types/base/project.py
- mapswipe_workers/mapswipe_workers/project_types/tile_map_service_grid/project.py
- mapswipe_workers/mapswipe_workers/utils/slack_helper.py
- mapswipe_workers/tests/unittests/fixtures/tile_map_service_grid/extent_too_big.geojson
- mapswipe_workers/tests/unittests/fixtures/tile_map_service_grid/invalid_geojson.geojson
- mapswipe_workers/tests/unittests/fixtures/tile_map_service_grid/projects/projectDraft_area_too_large.json
- mapswipe_workers/tests/unittests/fixtures/tile_map_service_grid/projects/projectDraft_broken_geojson.json
- mapswipe_workers/tests/unittests/fixtures/tile_map_service_grid/projects/projectDraft_feature_is_none.json
- mapswipe_workers/tests/unittests/fixtures/tile_map_service_grid/projects/projectDraft_no_features.json
- mapswipe_workers/tests/unittests/test_validate_geometries.py
This relates to #363 and #421 
I also add some more details to the error message we send to slack #316 
I can't reproduce #363, but still think that the tests should cover it now.
> Fix project creation invalid geometries bug

- mapswipe_workers/mapswipe_workers/project_types/arbitrary_geometry/grouping_functions.py
> Fix duplicated feature ids

- manager_dashboard/manager_dashboard/js/uploadProjects.js
- mapswipe_workers/mapswipe_workers/project_types/base/tile_server.py
- mapswipe_workers/tests/unittests/test_check_imagery_url.py
Check imagery url parameters in manager dashboard and during project creation in the back end.
This PR addresses #450
> Custom imagery url parameters

- .travis.yml
- ansible/playbook.yml
- docker-compose.yaml
- mapswipe_workers/mapswipe_workers/mapswipe_workers.py
- recreate_container.sh
The idea behind this is described in #457 
Basically, we just split the jobs into two docker containers.
> split workers into two separate docker containers

- manager_dashboard/manager_dashboard/create.html
- manager_dashboard/manager_dashboard/js/uploadProjects.js
fixes:
- #501
additionally fixed double point before gif
> catch missing image 

- mapswipe_workers/mapswipe_workers/definitions.py
- mapswipe_workers/mapswipe_workers/utils/slack_helper.py
- mapswipe_workers/python_scripts/update_project_status.py
Providing a script which will allow us to update the status of a project in Firebae (active --> finished, inactive --> active).
This script can be run in a docker container in situations we foresee a lot of mapping activity. For such a situation we might not be quick enough to update project status manually.
> Automatically update project status

- .github/workflows/actions.yml
- mapswipe_workers/.pre-commit-config.yaml
- mapswipe_workers/mapswipe_workers/firebase_to_postgres/transfer_results.py
- mapswipe_workers/mapswipe_workers/generate_stats/project_stats.py
- mapswipe_workers/mapswipe_workers/mapswipe_workers.py
- mapswipe_workers/mapswipe_workers/project_types/arbitrary_geometry/group.py
- mapswipe_workers/mapswipe_workers/project_types/arbitrary_geometry/task.py
- mapswipe_workers/mapswipe_workers/project_types/base/project.py
- mapswipe_workers/mapswipe_workers/utils/geojson_functions.py
- mapswipe_workers/mapswipe_workers/utils/tile_functions.py
- mapswipe_workers/python_scripts/update_project_status.py
- mapswipe_workers/requirements.txt
- mapswipe_workers/tests/integration/set_up.py
- mapswipe_workers/tests/integration/test_transfer_results_invalid_results.py
- mapswipe_workers/tests/integration/test_update_project_data.py
- mapswipe_workers/tests/unittests/test_check_imagery_url.py
> handling invalid matches

- manager_dashboard/manager_dashboard/js/forms.js
- manager_dashboard/manager_dashboard/js/uploadProjects.js
- mapswipe_workers/mapswipe_workers/project_types/base/project.py
Hey @laurentS ,
this should be a quick one. :) I've adjusted the manager dashboard and the back end workers slightly to allow the maxTasksPerUser attribute also for private projects.
> allow to set maxTasksPerUser for all project

- mapswipe-dashboard/app/hooks/useUrlState.ts
- mapswipe-dashboard/app/views/Dashboard/index.tsx
- mapswipe-dashboard/app/views/UserDashboard/index.tsx
- mapswipe-dashboard/app/views/UserGroupDashboard/index.tsx
- Use useUrlState in Dashboard
- Use useUrlState in UserDashboard
- Use useUrlState in UserGroupDashboard
> Add useUrlState

- nginx/nginx.conf.template
Addresses:
- Redirect old URL to current Manager Dashboard.
> Redirect to new Manager Dashboard.

- mapswipe_workers/python_scripts/results_to_mapping_sessions_results.py
- postgres/scripts/v2_to_v3/04b_fix_timestamps_for_mapping_sessions.sql
- postgres/scripts/v2_to_v3/05_fix_timestamps_for_mapping_sessions.sql
first run the sql script to add the start_time and end_time attributes in the mapping_sessions table, then run the python script to copy results into mapping_sessions_results table
> add script to transfer results to new schema

- firebase/functions/.eslintrc.js
- firebase/functions/tsconfig.json
- manager-dashboard/app/components/TileServerInput/index.tsx
- manager-dashboard/app/views/NewProject/index.tsx
- manager-dashboard/app/views/NewTutorial/index.tsx
Related to https://github.com/mapswipe/python-mapswipe-workers/issues/617
Related to https://github.com/mapswipe/python-mapswipe-workers/issues/618
- Change label for TileServerA and TileServerB
> Fix validation for imagery url

- community-dashboard/app/Base/utils/temporal.ts
- community-dashboard/app/components/Calendar/index.tsx
- community-dashboard/app/components/CalendarHeatMapContainer/index.tsx
- community-dashboard/app/components/Page/index.tsx
- community-dashboard/app/views/StatsBoard/index.tsx
Address
- https://github.com/mapswipe/mapswipe-meta/issues/106
- https://github.com/mapswipe/mapswipe-meta/issues/108
- https://github.com/mapswipe/python-mapswipe-workers/issues/624
- https://github.com/mapswipe/python-mapswipe-workers/issues/625
> Fix community dashboard timezone issue

- community-dashboard/app/Base/utils/temporal.ts
- community-dashboard/app/components/CalendarHeatMapContainer/index.tsx
- community-dashboard/app/components/CalendarHeatMapContainer/styles.css
- community-dashboard/app/components/InformationCard/styles.css
- community-dashboard/app/components/SelectInput/SearchSelectInput.tsx
- community-dashboard/app/views/StatsBoard/index.tsx
- community-dashboard/app/views/StatsBoard/styles.css
- community-dashboard/app/views/UserGroupDashboard/index.tsx
- django/apps/existing_database/query.py
- django/apps/existing_database/types.py
Address
- Fix day shift issue in time-series
- Using setUTCHours will use UTC as reference while setting the values
- Use **MapSwipe** as the default organization
- Add scrollbar on Calendar Heatmap
- https://github.com/mapswipe/mapswipe-meta/issues/111
> Manually set hours, minutes, seconds and milliseconds to zero

- manager-dashboard/app/views/NewProject/index.tsx
- manager-dashboard/app/views/NewProject/utils.ts
- manager-dashboard/app/views/UserGroups/UserGroupFormModal/index.tsx
- Change max characters to 40 for usergroup name
- Pass geometry received from ohsome if "inputType" is "TMId"
- https://github.com/mapswipe/mapswipe-meta/issues/114
- https://github.com/mapswipe/mapswipe-meta/issues/113
> Pass geometry received from ohsome if "inputType" is "TMId"

- manager-dashboard/README.md
- manager-dashboard/app/views/NewProject/index.tsx
- manager-dashboard/app/views/NewTutorial/index.tsx
- manager-dashboard/package.json
- Update README
- Update package.json
Addresses: https://github.com/mapswipe/python-mapswipe-workers/issues/659
> Add namespace for file name in the storage

- community-dashboard/app/components/ContributionHeatMap/index.tsx
Related https://github.com/mapswipe/mapswipe-meta/issues/72#issuecomment-1314750831
> Move heat map when user pans through world copies

- mapswipe_workers/mapswipe_workers/project_types/base/project.py
- mapswipe_workers/mapswipe_workers/project_types/tile_classification/project.py
Reverts mapswipe/python-mapswipe-workers#789
> Revert "Refactor python workers"

- mapswipe_workers/mapswipe_workers/project_types/base/project.py
- mapswipe_workers/mapswipe_workers/project_types/tile_classification/project.py
Reverts mapswipe/python-mapswipe-workers#790
> Revert "Revert "Refactor python workers""

- manager-dashboard/app/components/GeoJsonPreview/index.tsx
- manager-dashboard/app/views/NewProject/BasicProjectInfoForm/index.tsx
- manager-dashboard/app/views/NewProject/utils.ts
- manager-dashboard/app/views/NewTutorial/ScenarioPageInput/FootprintGeoJsonPreview/index.tsx
- manager-dashboard/app/views/NewTutorial/ScenarioPageInput/index.tsx
- manager-dashboard/app/views/NewTutorial/index.tsx
- manager-dashboard/app/views/NewTutorial/styles.css
- manager-dashboard/app/views/NewTutorial/utils.ts
- Add padding on footprint geojson preview
- Increase max characters for tutorial texts
- Remove note on footprint tutorial
- Send rgb color instead of names
> Only show instructions for footprint tutorial

- mapswipe_workers/mapswipe_workers/generate_stats/tasking_manager_geometries.py
Related to https://github.com/mapswipe/python-mapswipe-workers/issues/909
> Fix _share values

- mapswipe_workers/mapswipe_workers/generate_stats/tasking_manager_geometries.py
Related to
- https://github.com/mapswipe/python-mapswipe-workers/issues/909
> Fix bug when parsing _count & _share values

- django/mapswipe/sentry.py
Address
- https://github.com/mapswipe/mapswipe/issues/822
> Ignore User.DoesNotExist in sentry

- django/mapswipe/sentry.py
- mapswipe_workers/mapswipe_workers/generate_stats/tasking_manager_geometries.py
Includes
- https://github.com/mapswipe/python-mapswipe-workers/pull/914
NOTE: Don't delete `dev` branch
> Release - Minor change

- community-dashboard/app/views/StatsBoard/index.tsx
- https://github.com/mapswipe/python-mapswipe-workers/pull/917 - (already merged mistakenly)
- https://github.com/mapswipe/python-mapswipe-workers/pull/918
- https://github.com/mapswipe/mapswipe/issues/812
- Change terminology
- Mission Type to Project Type
- Build Area to Find
- Footprint to Validate
- Change Detection to Compare
> Release - Update terminology

- Makefile
- mapswipe_workers/mapswipe_workers/utils/user_management.py
- mapswipe_workers/python_scripts/list_all_project_managers.py
this adds a script to list all users with project managers rights.
> List project managers

- community-dashboard/app/Base/configs/apollo.ts
- community-dashboard/app/components/ItemSelectInput/index.tsx
- community-dashboard/app/components/SelectInput/SearchSelectInput.tsx
- community-dashboard/app/components/SelectInputContainer/EmptyOptions/index.tsx
- community-dashboard/app/components/SelectInputContainer/EmptyOptions/styles.css
- community-dashboard/app/components/SelectInputContainer/index.tsx
- https://github.com/mapswipe/python-mapswipe-workers/pull/927
- https://github.com/mapswipe/python-mapswipe-workers/issues/907
- Add show more clickable button component on `SearchSelectInput` component
- Fetch more data click on show more
> Add show more options on search select dropdown.

- firebase/functions/package.json
- firebase/functions/src/index.ts
- firebase/functions/yarn.lock
- manager-dashboard/app/views/NewProject/index.tsx
- https://github.com/mapswipe/python-mapswipe-workers/issues/929
- Add validation to create a unique project with the title
- Update node version to 18
- Update firebase-functions package 3.24.1
- Add `ProjectTopicKey` in all projects data
> Add validation for unique project while creating

- firebase/functions/src/index.ts
- mapswipe_workers/Dockerfile
- Add cloud function to save username in lower case
- This is to validate the username  unique for sign up.
> Add cloud function to save username in lowercase

- firebase/database.rules.json
- firebase/functions/src/index.ts
- firebase/functions/src/utils/index.ts
- manager-dashboard/app/utils/common.tsx
- manager-dashboard/app/views/NewProject/index.tsx
- manager-dashboard/app/views/NewProject/utils.ts
- mapswipe_workers/mapswipe_workers/project_types/project.py
- Fix condition to compare project title unique and save to draft
- Remove multiple space from project topic
- Cloud function 
- Change username to lowercase and remove space
- Change project topuc to lowercase and change multiples space to single
> Fix project draft topic save

- mapswipe_workers/mapswipe_workers/generate_stats/overall_stats.py
- https://mapswipe.slack.com/archives/C0HCW2CJJ/p1724063161392079
> Add organization_name in projects.csv

- community-dashboard/app/components/ItemSelectInput/index.tsx
- community-dashboard/app/components/MemberItem/index.tsx
- community-dashboard/app/views/UserDashboard/index.tsx
- community-dashboard/app/views/UserGroupDashboard/index.tsx
- https://github.com/mapswipe/python-mapswipe-workers/issues/687
- Fix user name display in the member list for OSM users on user group dashboard
> Fix username display on user group dashboard table

- firebase/functions/src/index.ts
This will help debugging https://github.com/mapswipe/python-mapswipe-workers/issues/1016
> Hotfix: Improve firebase logging for contribution rejections
